name: Build docker images

on:
  create:
    tags:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/checkout@v3
    - name: Build and push the InstaAPI docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        file: ./Dockerfile
        tags: | 
          ghcr.io/svenlie/instagrapi:${{ github.ref_name }}
          ghcr.io/svenlie/instagrapi:latest
